language: node_js
dist: trusty
cache:
  directories:
    - node_modules

matrix:
  include:
    - node_js: "lts/*"
      env: YARN_TASK=test:node
    - node_js: "node"
      env: YARN_TASK=test:node
    - node_js: "node"
      env: YARN_TASK=test:browser
      addons:
        chrome: stable

install: yarn --frozen-lockfile --ignore-optional

script: yarn run build && yarn run $YARN_TASK

after_success: yarn run coveralls
